/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 rob.glb --transform 
Files: rob.glb [1.92MB] > D:\MernStack\3\model\public\models\robot\rob-transformed.glb [108.15KB] (94%)
Author: Gostbento (https://sketchfab.com/gostbento)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/delivery-robot-4dbac67355174751801fb1f6e8dc6230
Title: Delivery robot
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene } = useGLTF('./models/robot/rob-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials, animations } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.002']} skeleton={nodes.Object_9.skeleton} position={[0, -0.269, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.228} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/robot/rob-transformed.glb')
